name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Test
        run: go test
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: autopark-x86-64-linux
          path: autopark-x86-64-linux
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: autopark-aarch64-linux
          path: autopark-aarch64-linux
          if-no-files-found: error
